### ISSUE TITLE
Port of old fortran code to something else?

### ISSUE THREAD

**Issue by potmo** [wmay/nominate#1]
Hi, 
I have been looking for the source code for the dw-nominate in any other language than fortran and I stumbled upon this repo. I see that you have done a wrapper around the original fortran program and I was wondering if you have considered porting the dw-nominate algorithm to something less intimidating like ruby, java, c or similar? I guess, since yo have done the wrapper, you must have some knowledge of fortran maybe? 

I  haven't really found a good source for the actual algorithm. Do you have any links to any papers or such? I can only find papers for w-nominate and not the dw-nominate algorithm.

Thanks in advance.

**Comment by wmay** [comment]
Egad, I wish I was good with Fortran and could do that. It looks like spaghetti code to me, and that's partly why I wrote the gem.

Keith Poole has a cool book called "Spatial Models of Parliamentary Voting" that explains a lot of the math. I don't think it specifically goes through all the details of DW-NOMINATE, but it's the most in-depth discussion I'm aware of.

I get the impression that people are moving towards Bayesian models now, anyway. If you're lucky, that will solve your problem. Or maybe ask Keith Poole.
