### ISSUE TITLE
Unable to compile DW-NOMINATE.F

### ISSUE THREAD

**Issue by vitorbaptista** [wmay/nominate#2]
Hi,

I'm trying to run your code and it fails when compiling DW-NOMINATE.F. I tried reproducing it on bash and I get:

```
vitor@clarisse:/tmp$ gfortran DW-NOMINATE.FOR -w -o dw-nominate
/tmp/cc1HtXAL.o: In function `MAIN__':
DW-NOMINATE.FOR:(.text+0x1cd5e): undefined reference to `gettim_'
DW-NOMINATE.FOR:(.text+0x26188): undefined reference to `gettim_'
collect2: error: ld returned 1 exit status
```

My gfortran version is `GNU Fortran (Ubuntu 4.8.2-19ubuntu1) 4.8.2`. You've probably used a different version than I did. Could you check what version was it? I understand that this repository was created a while ago and you probably don't have time to check its issues, but if you could simply document your gfortran version it would help a lot :smiley:

Thanks for your time.

**Comment by vitorbaptista** [comment]
I tested with `GNU Fortran (Ubuntu/Linaro 4.6.4-6ubuntu2) 4.6.4` and `GNU Fortran (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3` as well, and had the same issue.

I just noticed that the `DW-NOMINATE.FOR` you provide in this repository is different from the one at ftp://voteview.com/wf1/DW-NOMINATE.FOR. It doesn't have the `call gettim(itim1,itim2,itim3,itim4)` commands at lines 141 and 947. I can compile your version, but are you sure this doesn't influence the results?

``` diff
141d140
<       call gettim(itim1,itim2,itim3,itim4)
947d945
<       call gettim(jtim1,jtim2,jtim3,jtim4)
```

**Comment by wmay** [comment]
I had to remove the gettim functions from the original Fortran program to get it to compile. I was looking at  the original Fortran code again around the time I last updated this, so I'm sure that's how I got them confused.

Anyway, gettim() appears to be a function that returns the time. It's just there to keep track of the running time of the program.

**Comment by vitorbaptista** [comment]
Thanks @wmay. This makes sense.

Now I just have to understand how I can use DW-NOMINATE on other legislatures (i.e. not from the US). It feels too coupled to it, unfortunately :/

I'll close this issue now.

**Comment by wmay** [comment]
I've seen a rollcall scaling of Canadian legislators. It does seem to be less useful, both because the parties are more cohesive in parliamentary systems (less individual variation to discover), and the axes are harder to interpret.

http://www.cpsa-acsp.ca/papers-2008/Godbout.pdf

But I'm curious to see what the results of DW-NOMINATE would look like in that situation.
